import {useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import api from '../libs/axios';
import toast from 'react-hot-toast';
import {openCurtainPrint} from '../libs/curtainPrint';
const money=x=>Number(x||0).toLocaleString('tr-TR',{style:'currency',currency:'TRY'});
const statuses={beklemede:'Beklemede',tamamlandi:'Sipariş onaylandı',kaybedildi:'Kaybedilen teklifler'};
export default function SalesPage(){
  const [sales,setSales]=useState([]),[loading,setLoading]=useState(true),[tab,setTab]=useState('beklemede'),[search,setSearch]=useState(''),[month,setMonth]=useState(new Date().toLocaleDateString('sv-SE').slice(0,7)),[busy,setBusy]=useState(null);
  const navigate=useNavigate();
  const load=async()=>{try{const r=await api.get('/sales');setSales(r.data);}catch{toast.error('Teklif ve siparişler yüklenemedi.');}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const monthly=sales.filter(x=>new Date(x.createdAt).toLocaleDateString('sv-SE').slice(0,7)===month);
  const total=monthly.reduce((s,x)=>s+Number(x.grand_total||0),0),approved=monthly.filter(x=>x.status==='tamamlandi'),won=sales.filter(x=>x.status==='tamamlandi'&&new Date(x.approved_at||x.updatedAt||x.createdAt).toLocaleDateString('sv-SE').slice(0,7)===month).reduce((s,x)=>s+x.grand_total,0);
  const matches=sales.filter(x=>x.status===tab&&(!search||`${x.customer_name} ${x.customer_phone} ${x._id}`.toLocaleLowerCase('tr-TR').includes(search.toLocaleLowerCase('tr-TR'))));
  const lose=async(sale)=>{setBusy(sale._id);try{await api.put(`/sales/${sale._id}`,{status:'kaybedildi'});await load();toast.success('Teklif kaybedildi olarak kaydedildi.');}catch(error){toast.error(error.response?.data?.message||'Durum kaydedilemedi.');}finally{setBusy(null);}};
  return <div className="space-y-5">
    <div><h1 className="text-3xl font-bold">Teklif ve sipariş takibi</h1><p className="mt-2 text-gray-600">Bekleyen teklifleri, onaylanan siparişleri ve geri dönüşleri bu ayrı ekrandan izleyin.</p></div>
    <section className="bg-white rounded-2xl p-5 border"><label className="flex gap-3 items-center mb-4">Rapor ayı<input aria-label="Rapor ayı" type="month" value={month} onChange={e=>setMonth(e.target.value)} className="border rounded-lg px-3"/></label><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[['Teklif / sipariş toplamı',money(total)],['Onaylanan iş tutarı',money(won)],['Dönüş oranı',`${monthly.length?Math.round(approved.length/monthly.length*100):0}%`],['Teklif / sipariş sayısı',String(monthly.length)]].map(([label,value])=><div key={label}><p className="text-sm text-gray-600">{label}</p><strong className="text-xl">{value}</strong></div>)}</div></section>
    <div className="flex flex-wrap gap-3">{Object.entries(statuses).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`px-5 rounded-xl border font-semibold ${tab===id?'bg-indigo-600 text-white':'bg-white'}`}>{label} ({sales.filter(x=>x.status===id).length})</button>)}</div>
    <input aria-label="Müşteri veya sipariş ara" placeholder="Müşteri adı, telefon veya sipariş numarası…" value={search} onChange={e=>setSearch(e.target.value)} className="w-full border rounded-xl px-4"/>
    {loading?<p>Yükleniyor…</p>:!matches.length?<div className="bg-white rounded-xl p-8 border">Bu bölümde kayıt bulunmuyor.</div>:<div className="space-y-4">{matches.map(sale=><article key={sale._id} className="bg-white rounded-2xl p-5 border"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="font-bold text-lg">{sale.customer_name||'Müşteri adı girilmedi'}</h2><p>#{sale._id.slice(-8).toUpperCase()} · {new Date(sale.createdAt).toLocaleDateString('tr-TR')}</p><p>Telefon: {sale.customer_phone||'—'} · Teslim: {sale.delivery_date?new Date(sale.delivery_date).toLocaleDateString('tr-TR'):'—'}</p><p>{sale.delivery_method==='montaj'||sale.delivery_method==='installation'?'Montaj':'Mağaza teslimi'} · {sale.sale_items.length} ürün kalemi</p></div><div className="text-right"><strong className="text-2xl">{money(sale.grand_total)}</strong><p>İskonto %{Number(sale.discount_percent||0).toLocaleString('tr-TR')} · {money(sale.discount_amount)}</p></div></div><div className="flex flex-wrap gap-3 mt-4">{sale.status!=='tamamlandi'?<><button disabled={busy===sale._id} onClick={()=>navigate('/dashboard/pos',{state:{pendingSale:sale}})} className="bg-indigo-600 text-white px-5 rounded-lg">Teklifi aç / Düzenle</button>{sale.status==='beklemede'&&<button disabled={busy===sale._id} onClick={()=>lose(sale)} className="border px-4 rounded-lg">Kaybedildi olarak işaretle</button>}</>:<><button onClick={()=>openCurtainPrint(sale,'customer')} className="border px-4 rounded-lg">Müşteri sipariş kağıdı / PDF</button><button onClick={()=>openCurtainPrint(sale,'manufacturing')} className="border px-4 rounded-lg">İmalat planı / PDF</button></>}</div></article>)}</div>}
  </div>;
}
